:toc:

= Программа курса "Kotlin School"

== Описание курса

Базовый курс рассчитан на знакомство с основными возможностями языка Kotlin, знакомство с функциональным программированием, переход/совмещение с Java в проекте, обсуждение популярных библиотек и инфраструктуру для разработке на языке.

Главной целью курса является научить разработчиков использовать идиоматические подходы Kotlin и использовать его подходы, вместо того чтобы писать Kotlin код в Java стиле.

В рамках курсах будет рассказываться о Kotlin 1.3.

== Требования к слушателям

Разработчики, имеющие опыт создания приложения на Java: бекенд, десктопные или Android, или имеющие опыт использования Kotlin, но только его базового функционала.

== Цели

* Повысить культуры использования языка Kotlin
* Создание новых разработчиков, способных писать на Kotlin
* Популяризация Kotlin
* Привлечение новых людей в сообщество BKUG

== Ожидаемые результаты по окончанию курса

В конце курса ожидается, что слушатели, прошедшие его смогут:

* Использовать Kotlin в проекте
* Совмещать Kotlin код c Java
* Переводить Java код в Kotlin
* Эффективно использовать функционал из стандартной библиотеки Kotlin
* Применять функциональные подходы программирования Kotlin в проектах

== Лекции

=== Формат проведения лекций

Лекция длится около 1-1.5 часа. В рамках нее происходит обсуждение темы и должно выдаваться домашнее задание.

*Порядок тем в лекциях произвольный*

include::l1.adoc[]
include::l2.adoc[]
include::l3.adoc[]
include::l4.adoc[]
include::l5.adoc[]
include::l6.adoc[]
include::l7.adoc[]
include::l8.adoc[]
include::l9.adoc[]

== Команда курса

=== Лекторы

* Кирилл Розов link:mailto:krl.rozov@gmail.com[krl.rozov@gmail.com]
* Руслан Ибрагимов link:mailto:ruslan@ibragimov.by[ruslan@ibragimov.by]
* Сергей Крюков link:mailto:siarhei.krukau@gmail.com[siarhei.krukau@gmail.com]

=== Менторы
